name: Run Alive Blog Bot

on:
  workflow_dispatch:   # lets you run manually
  schedule:
    - cron: "0 14 * * *"  # Runs every day at 10AM EST

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install openai feedparser requests

    - name: Run bot
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python alive_blog_bot.py

    - name: Commit updated CSV
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add linkedin_posts.csv
        git commit -m "Update LinkedIn posts CSV" || echo "No changes"
        git push
